### ISSUE TITLE
Will not build in Xcode 11 beta 4

### ISSUE THREAD

**Issue by peternicholls** [bpisano/Weather#5]
### Swift Compiler Error Group

- Model/City/Store/City.swift:12:7: Type 'City' does not conform to protocol 'BindableObject'
- Model/City/Store/City.swift:12:7: Do you want to add protocol stubs?
- Views/CityHeaderView.swift:41:24: Missing argument for parameter 'city' in call
- Views/CityHeaderView.swift:11:8: 'init(city:)' declared here
- Model/City/Completion/CityCompletion.swift:12:7: Type 'CityCompletion' does not conform to protocol 'BindableObject'
- Model/City/Completion/CityCompletion.swift:12:7: Do you want to add protocol stubs?
- Views/CityWeatherView.swift:39:25: Missing argument for parameter 'city' in call
- Views/CityWeatherView.swift:11:8: 'init(city:)' declared here
- Views/List/CityRow.swift:40:17: Missing argument for parameter 'city' in call
- Views/List/CityRow.swift:11:8: 'init(city:)' declared here
- Model/City/Store/CityStore.swift:12:7: Type 'CityStore' does not conform to protocol 'BindableObject'
- Model/City/Store/CityStore.swift:12:7: Do you want to add protocol stubs?
- Views/List/NewCityView.swift:78:9: Use of unresolved identifier 'AddCityView'
- Views/CityHourlyView.swift:42:24: Missing argument for parameter 'city' in call
- Views/CityHourlyView.swift:11:8: 'init(city:)' declared here
- Views/CityDailyView.swift:49:23: Missing argument for parameter 'day' in call
- Views/CityDailyView.swift:11:8: 'init(day:)' declared here

### Swift Compiler Warning Group

- Views/List/CityRow.swift:27:26: 'color' is deprecated: renamed to 'foregroundColor'
- Views/List/CityRow.swift:27:26: Use 'foregroundColor' instead
- Views/List/CityListView.swift:62:30: 'Modal' is deprecated: Use View.sheet instead.
- Views/List/CityListView.swift:42:14: 'presentation' is deprecated: Use View.sheet instead.
- Views/List/CityListView.swift:63:9: 'Modal' is deprecated: Use View.sheet instead.
- Views/CityDailyView.swift:38:18: 'color' is deprecated: renamed to 'foregroundColor'
- Views/CityDailyView.swift:38:18: Use 'foregroundColor' instead

**Comment by young40** [comment]
please change all `didChange ` to `willChange`

@peternicholls

**Comment by bpisano** [comment]
Thanks. I’ll fix this as soon as I can download the Xcode 11 beta 4. You can make a pull request if you want too.

**Comment by bpisano** [comment]
Fixed in my last commit.
